### ISSUE TITLE
role public is written as "PUBLIC"

### ISSUE THREAD

**Issue by ehansmair** [rvkulikov/pg-deps-management#13]
The role public is written as "PUBLIC":
GRANT UPDATE ON phpunit.aa_view TO "PUBLIC" 
GRANT DELETE ON phpunit.aa_view TO "PUBLIC" 

This gives an error in deps_restore_dependencies():

DEBUG:  Executing ddl statement: GRANT REFERENCES (a) ON phpunit.b_view TO "PUBLIC" 

ERROR: FEHLER:  Rolle »PUBLIC« existiert nicht
CONTEXT:  SQL-Anweisung »GRANT REFERENCES (a) ON phpunit.b_view TO "PUBLIC" «
PL/pgSQL-Funktion deps_restore_dependencies(name,name,jsonb) Zeile 35 bei EXECUTE

**Comment by rvkulikov** [comment]
@ehansmair issue accepted. Will be fixed today

**Comment by rvkulikov** [comment]
That one was fun to fix.
Fixed
