### ISSUE TITLE
RDS

### ISSUE THREAD

**Issue by reubent** [rvkulikov/pg-deps-management#16]
Hi,

We run postgres on RDS, which does not make `pg_authid` available but does make the `pg_role` view that relies on it visible. I've changed the code locally to use `pg_role` and it appears to work fine with that instead.

I'm happy to submit a pull request to make the change if you're open to doing this by default but thought I should check first before sending you random code :)

**Comment by rvkulikov** [comment]
Hi there! Yep, submit pull request and I'll merge it.

**Comment by c16harrigan** [comment]
Just ran into this same issue! Will keep on eye out for the pull request

**Comment by rvkulikov** [comment]
well, perhaps I can do it by myself.
@c16harrigan could you test dev version on your env in the next couple of days?

**Comment by c16harrigan** [comment]
@rvkulikov definitely!

**Comment by rvkulikov** [comment]
@reubent @c16harrigan Done.
